version: '3'
services:
  backend:
    build: ../backend
    ports:
      - "3001:3001"
    environment:
      - AWS_ACCESS_KEY_ID=your-access-id
      - AWS_SECRET_ACCESS_KEY=your-secret-access-key

  frontend:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "80:80"
