version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "80:80"
